### ISSUE TITLE
[BUG] Error when no LR to display

### ISSUE THREAD

**Issue by Toxiic57** [Sples1/ENT_LR-Statistics#1]
I got this error when i just installed the plugin and dont any LR to display 

`
L 10/07/2020 - 22:04:04: [lr_stats.smx] Erreur: no such table: lr_stats
L 10/07/2020 - 22:04:04: [SM] Exception reported: Invalid query Handle 0 (error: 4)
L 10/07/2020 - 22:04:04: [SM] Blaming: lr_stats.smx
L 10/07/2020 - 22:04:04: [SM] Call stack trace:
L 10/07/2020 - 22:04:04: [SM]   [0] DBResultSet.RowCount.get
L 10/07/2020 - 22:04:04: [SM]   [1] Line 479, C:\Users\Sples\Desktop\Scripting\Random Scripting\lr_stats.sp::GetSBStat_Callback
`

**Comment by Toxiic57** [comment]
And when i check somebody else stat i got my name on the top of the panel 

https://gyazo.com/25fa2ff6bb4a0c2924756d64c763f360

**Comment by Sples1** [comment]
Fixed and uploaded <3
